import { ArrowLeft, Check, Edit3, ExternalLink, Save, Download, Globe, Loader2, CheckCircle } from 'lucide-react';
import { useNavigate } from 'react-router';
import { useState, useEffect } from 'react';
import MiniFlowGraph from '../components/MiniFlowGraph';
import { api, type STREvent, type Case } from '../../services/api';

const DEFAULT_CASE = 'CASE-2847';

type Stage = 'idle' | 'analysing_pattern' | 'compiling_evidence' | 'drafting_narrative' | 'complete' | 'error';

const STAGE_ORDER: Stage[] = ['analysing_pattern', 'compiling_evidence', 'drafting_narrative', 'complete'];

function stageIndex(s: Stage): number {
  return STAGE_ORDER.indexOf(s);
}

// Save/load from localStorage
function saveDraft(caseId: string, data: any) {
  const key = `str_draft_${caseId}`;
  localStorage.setItem(key, JSON.stringify({
    ...data,
    savedAt: new Date().toISOString(),
  }));
}

function loadDraft(caseId: string): any | null {
  const key = `str_draft_${caseId}`;
  const saved = localStorage.getItem(key);
  return saved ? JSON.parse(saved) : null;
}

// Generate PDF (client-side)
function exportToPDF(caseData: Case | null, report: any, language: 'EN' | 'HI') {
  const narrative = typeof report === 'string' 
    ? report 
    : (report as any)?.english_narrative || (report as any)?.summary || 'No narrative';
  
  const riskRating = typeof report === 'object' ? (report as any)?.risk_rating || 'High' : 'High';
  const recommendedAction = typeof report === 'object' 
    ? (report as any)?.recommended_action || 'Escalate for manual review.' 
    : 'Escalate for manual review.';

  const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  
  const content = `
FIU-IND FORM STR-01 (${language})

Report Date: ${today}
Filing Entity: Union Bank of India

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CASE REF: ${caseData?.case_id || DEFAULT_CASE}
TYPOLOGY: ${caseData?.typology || 'Round-trip Layering'}
TOTAL AMOUNT: ${caseData?.total_amount ? `₹${caseData.total_amount.toLocaleString('en-IN')}` : '₹47,23,000'}
STATUS: ${caseData?.status?.toUpperCase() || 'OPEN'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

NARRATIVE:

${narrative}

RISK RATING: ${riskRating}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RECOMMENDED ACTION:

${recommendedAction}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by FundLens AML Platform
Union Bank of India
Regulatory Compliance: PMLA Section 16, FATF Typology 12

This document is confidential and intended for FIU-IND submission only.
  `.trim();

  // Create blob and download
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `STR_${caseData?.case_id || DEFAULT_CASE}_${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Submit to FIU-IND (mock submission that creates a record)
async function submitToFIU(caseId: string, report: any): Promise<boolean> {
  // In production, this would call a real FIU-IND API
  // For now, we'll simulate by saving to localStorage with a submission timestamp
  const submission = {
    caseId,
    report,
    submittedAt: new Date().toISOString(),
    submittedBy: 'System User',
    fiuReference: `FIU-${Date.now()}`,
    blockchainHash: `0x${Math.random().toString(16).slice(2, 18)}...`,
  };
  
  localStorage.setItem(`str_submission_${caseId}`, JSON.stringify(submission));
  
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  return true;
}

export default function STRGeneration() {
  const navigate = useNavigate();
  const [language, setLanguage] = useState<'EN' | 'HI'>('EN');

  const [stage, setStage]         = useState<Stage>('idle');
  const [progress, setProgress]   = useState(0);
  const [report, setReport]       = useState<string | Record<string, any> | null>(null);
  const [caseData, setCaseData]   = useState<Case | null>(null);
  const [generating, setGenerating] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted]  = useState(false);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved'>('idle');

  const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

  // Load case details and check for saved draft
  useEffect(() => {
    api.getCase(DEFAULT_CASE)
      .then(setCaseData)
      .catch(() => { /* use static fallback */ });
    
    // Check for saved draft
    const draft = loadDraft(DEFAULT_CASE);
    if (draft && draft.report) {
      setReport(draft.report);
      setStage('complete');
      setProgress(100);
    }
    
    // Check if already submitted
    const submission = localStorage.getItem(`str_submission_${DEFAULT_CASE}`);
    if (submission) {
      setSubmitted(true);
    }
  }, []);

  const handleGenerate = () => {
    if (generating) return;
    setGenerating(true);
    setStage('analysing_pattern');
    setProgress(0);
    setReport(null);

    api.generateSTR(DEFAULT_CASE, (event: STREvent) => {
      setStage(event.stage);
      setProgress(event.progress);
      if (event.report) {
        setReport(event.report);
        // Auto-save when complete
        saveDraft(DEFAULT_CASE, { report: event.report, caseData });
      }
    })
      .catch(() => setStage('error'))
      .finally(() => setGenerating(false));
  };

  const handleSaveDraft = () => {
    if (!report) {
      alert('No report to save. Generate a report first.');
      return;
    }
    setSaveStatus('saving');
    saveDraft(DEFAULT_CASE, { report, caseData });
    setTimeout(() => {
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2000);
    }, 500);
  };

  const handleExportPDF = () => {
    if (!report) {
      alert('No report to export. Generate a report first.');
      return;
    }
    exportToPDF(caseData, report, language);
  };

  const handleSubmit = async () => {
    if (!report) {
      alert('No report to submit. Generate a report first.');
      return;
    }
    
    if (!confirm('Submit this STR to FIU-IND? This will create an immutable blockchain record.')) {
      return;
    }

    setSubmitting(true);
    try {
      const success = await submitToFIU(DEFAULT_CASE, report);
      if (success) {
        setSubmitted(true);
        alert('✅ STR successfully submitted to FIU-IND!\n\nSubmission recorded on blockchain.\nReference: FIU-' + Date.now());
      }
    } catch (error) {
      alert('❌ Submission failed. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  const activeStepIdx = stageIndex(stage);

  const steps = [
    { label: 'Analysing pattern',  key: 'analysing_pattern'  as Stage },
    { label: 'Compiling evidence', key: 'compiling_evidence' as Stage },
    { label: 'Drafting narrative', key: 'drafting_narrative' as Stage },
  ];

  return (
    <div className="min-h-screen bg-white">
      {/* Top Bar */}
      <div className="h-[64px] bg-white border-b border-gray-200 flex items-center justify-between px-8">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate('/')} className="flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            <span className="text-sm">Back to Investigation</span>
          </button>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={handleSaveDraft}
            disabled={!report || saveStatus === 'saving'}
            className="px-4 py-2 border border-gray-400 text-gray-600 hover:bg-gray-100 transition-colors rounded text-sm flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {saveStatus === 'saving' ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : saveStatus === 'saved' ? (
              <CheckCircle className="w-4 h-4 text-green-600" />
            ) : (
              <Save className="w-4 h-4" />
            )}
            {saveStatus === 'saved' ? 'Saved!' : 'Save Draft'}
          </button>
          <button 
            onClick={handleExportPDF}
            disabled={!report}
            className="px-4 py-2 border border-gray-400 text-gray-600 hover:bg-gray-100 transition-colors rounded text-sm flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Download className="w-4 h-4" />
            Export PDF
          </button>
          <button 
            onClick={handleSubmit}
            disabled={!report || submitting || submitted}
            className="px-6 py-2 bg-[#E31E24] text-white hover:bg-[#d4183d] transition-colors rounded text-sm font-semibold flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed" 
            style={{ fontFamily: 'Syne' }}
          >
            {submitting ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Submitting...
              </>
            ) : submitted ? (
              <>
                <CheckCircle className="w-4 h-4" />
                Submitted
              </>
            ) : (
              <>
                Submit to FIU-IND
                <ExternalLink className="w-4 h-4" />
              </>
            )}
          </button>
        </div>
      </div>

      {/* 50/50 Split */}
      <div className="flex h-[calc(100vh-64px)]">

        {/* LEFT PANEL */}
        <div className="w-1/2 border-r border-gray-200 p-8 overflow-auto">
          
          {/* Submission status banner */}
          {submitted && (
            <div className="mb-6 bg-green-50 border-l-4 border-green-500 p-4 rounded">
              <div className="flex items-center gap-3">
                <CheckCircle className="w-5 h-5 text-green-600" />
                <div>
                  <div className="text-green-900 font-semibold text-sm">STR Submitted to FIU-IND</div>
                  <div className="text-green-700 text-xs mt-1">
                    Submission recorded on blockchain
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="mb-6">
            <h3 className="text-sm text-gray-600 mb-3">Case Overview</h3>
            <MiniFlowGraph />
          </div>

          {/* Case Summary — live from /api/cases */}
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-5 mb-6">
            <h3 className="text-sm text-gray-600 mb-4">Case Summary</h3>
            <div className="space-y-3 text-sm" style={{ fontFamily: 'DM Mono' }}>
              <div className="flex justify-between">
                <span className="text-gray-600">Case ID:</span>
                <span className="text-gray-900">{caseData?.case_id ?? DEFAULT_CASE}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Typology:</span>
                <span className="text-gray-900">{caseData?.typology ?? 'Round-trip Layering'}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Amount:</span>
                <span className="text-gray-900">
                  {caseData?.total_amount
                    ? `₹${caseData.total_amount.toLocaleString('en-IN')}`
                    : '₹47,23,000'}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Status:</span>
                <span className="text-gray-900 capitalize">{caseData?.status ?? 'open'}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Regulatory reference:</span>
                <span className="text-gray-900">PMLA S.16, FATF Typology 12</span>
              </div>
            </div>
          </div>

          {/* Evidence Chain */}
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-5">
            <h3 className="text-sm text-gray-600 mb-4">Evidence Chain</h3>
            <div className="space-y-3">
              {[
                { block: '#48291', time: '14:23:07' },
                { block: '#48292', time: '14:23:09' },
                { block: '#48293', time: '14:23:12' },
              ].map((item, idx) => (
                <div key={idx} className="flex items-center gap-3 bg-white border border-gray-200 rounded-md p-3">
                  <div className="w-6 h-6 flex items-center justify-center">
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                      <rect x="2" y="2" width="4" height="4" fill="#E31E24" />
                      <rect x="10" y="2" width="4" height="4" fill="#E31E24" />
                      <rect x="2" y="10" width="4" height="4" fill="#E31E24" />
                      <rect x="10" y="10" width="4" height="4" fill="#E31E24" />
                      <line x1="6" y1="4" x2="10" y2="4" stroke="#E31E24" />
                      <line x1="6" y1="12" x2="10" y2="12" stroke="#E31E24" />
                      <line x1="4" y1="6" x2="4" y2="10" stroke="#E31E24" />
                      <line x1="12" y1="6" x2="12" y2="10" stroke="#E31E24" />
                    </svg>
                  </div>
                  <div className="flex-1 text-xs" style={{ fontFamily: 'DM Mono' }}>
                    <div className="text-gray-900">Block {item.block} · Verified</div>
                  </div>
                  <Check className="w-4 h-4 text-[#E31E24]" />
                </div>
              ))}
            </div>
            <div className="mt-4 text-xs text-gray-600" style={{ fontFamily: 'DM Mono' }}>
              Evidence anchored to Hyperledger Fabric — tamper-proof since 14:23:07
            </div>
          </div>
        </div>

        {/* RIGHT PANEL */}
        <div className="w-1/2 p-8 overflow-auto flex flex-col">

          {/* Generate button (shown when idle) */}
          {stage === 'idle' && (
            <div className="mb-8 flex items-center gap-4">
              <button
                onClick={handleGenerate}
                className="px-6 py-3 bg-[#E31E24] text-white hover:bg-[#d4183d] transition-colors rounded-lg text-sm font-bold flex items-center gap-2"
                style={{ fontFamily: 'Syne' }}
              >
                Generate STR Report
              </button>
              <span className="text-xs text-gray-500">AI will draft the narrative using case data</span>
            </div>
          )}

          {/* Progress Stepper */}
          {stage !== 'idle' && (
            <div className="flex items-center gap-4 mb-8">
              {steps.map((step, idx) => {
                const done    = activeStepIdx > idx || stage === 'complete';
                const active  = activeStepIdx === idx && stage !== 'complete';
                return (
                  <div key={idx} className="flex items-center gap-2">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center ${done ? 'bg-[#E31E24]' : active ? 'border-2 border-[#E31E24] bg-white' : 'border-2 border-gray-300 bg-white'}`}>
                      {done ? (
                        <Check className="w-4 h-4 text-white" />
                      ) : active ? (
                        <div className="w-2 h-2 bg-[#E31E24] rounded-full animate-pulse" />
                      ) : (
                        <div className="w-2 h-2 bg-gray-300 rounded-full" />
                      )}
                    </div>
                    <span className={`text-xs ${active ? 'text-gray-900 font-medium' : 'text-gray-500'}`}>{step.label}</span>
                    {idx < steps.length - 1 && <div className={`w-8 h-[2px] ${done ? 'bg-[#E31E24]' : 'bg-gray-200'}`} />}
                  </div>
                );
              })}
              {generating && <Loader2 className="w-4 h-4 text-[#E31E24] animate-spin ml-2" />}
            </div>
          )}

          {/* Progress bar */}
          {stage !== 'idle' && stage !== 'complete' && (
            <div className="mb-6">
              <div className="h-1.5 bg-gray-200 rounded-full overflow-hidden">
                <div className="h-full bg-[#E31E24] transition-all duration-500 rounded-full" style={{ width: `${progress}%` }} />
              </div>
              <div className="text-xs text-gray-500 mt-1 text-right" style={{ fontFamily: 'DM Mono' }}>{progress}%</div>
            </div>
          )}

          {stage === 'error' && (
            <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600">
              STR generation failed. Check that the backend is running and the case exists.
            </div>
          )}

          {/* STR Report Preview */}
          <div className="flex-1 bg-gray-50 border border-[#E31E24] rounded-xl p-6">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-3">
                <div className="px-3 py-1 bg-[#E31E24] text-white rounded text-xs font-bold">
                  STR-01 {stage === 'complete' ? 'READY' : 'DRAFT'}
                </div>
                {stage === 'complete' && (
                  <div className="text-xs text-gray-600" style={{ fontFamily: 'DM Mono' }}>Auto-generated</div>
                )}
              </div>
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-1 bg-gray-200 rounded px-2 py-1">
                  <Globe className="w-3 h-3 text-gray-600" />
                  {(['EN', 'HI'] as const).map((lang, i) => (
                    <button
                      key={lang}
                      onClick={() => setLanguage(lang)}
                      className={`px-2 py-0.5 rounded text-xs transition-colors ${language === lang ? 'bg-[#E31E24] text-white font-bold' : 'text-gray-600'}`}
                    >
                      {lang}
                    </button>
                  ))}
                </div>
                <div className="px-3 py-1 bg-gray-200 text-gray-700 rounded text-xs">PMLA S.16 · goAML Format</div>
              </div>
            </div>

            <div className="mb-4 text-xs text-gray-600" style={{ fontFamily: 'DM Mono' }}>3 pages · 847 words</div>

            <div className="space-y-4 text-[11px] leading-relaxed text-gray-700" style={{ fontFamily: 'DM Mono' }}>
              <div className="text-gray-900 font-bold text-sm mb-4">FIU-IND FORM STR-01 (DRAFT)</div>
              <div>
                <div className="text-gray-900">Report Date: {today}</div>
                <div className="text-gray-900">Filing Entity: Union Bank of India</div>
              </div>
              <div className="h-[1px] bg-gray-300 my-4" />
              <div>
                <div className="text-gray-900 font-bold mb-2">CASE REF: {caseData?.case_id ?? DEFAULT_CASE}</div>
                <div>TYPOLOGY: {caseData?.typology ?? 'Round-trip Layering'}</div>
                <div>TOTAL AMOUNT: {caseData?.total_amount ? `₹${caseData.total_amount.toLocaleString('en-IN')}` : '₹47,23,000'}</div>
                <div>STATUS: {caseData?.status?.toUpperCase() ?? 'OPEN'}</div>
              </div>
              <div className="h-[1px] bg-gray-300 my-4" />
              <div>
                <div className="text-gray-900 font-bold mb-2">NARRATIVE:</div>
                {report ? (
                  <>
                    <div className="leading-relaxed opacity-90 whitespace-pre-wrap">
                      {typeof report === 'string' 
                        ? report 
                        : (report as any).english_narrative || (report as any).summary || 'No narrative generated'}
                    </div>
                    {typeof report === 'object' && (report as any).risk_rating && (
                      <div className="mt-3 pt-3 border-t border-gray-300">
                        <div className="text-gray-900 font-bold mb-1">Risk Rating:</div>
                        <div className="text-[#E31E24] font-semibold">{(report as any).risk_rating}</div>
                      </div>
                    )}
                  </>
                ) : (
                  <div className="leading-relaxed opacity-90">
                    FundLens detected a round-trip layering pattern involving seven accounts across three transaction hops.
                    The pattern commenced when a dormant savings account (ACC-0041) was suddenly activated and dispersed
                    funds totaling ₹47,23,000 to multiple intermediary accounts. These funds were subsequently consolidated
                    through a central hub account (ACC-0089) exhibiting high-risk characteristics.
                    <br /><br />
                    The consolidated amount was then distributed through additional intermediary layers before returning to
                    the origin account (ACC-0041), completing a suspicious circular flow within 6 hours 14 minutes.
                  </div>
                )}
              </div>
              <div className="h-[1px] bg-gray-300 my-4" />
              <div>
                <div className="text-gray-900 font-bold mb-2">RECOMMENDED ACTION:</div>
                {report && typeof report === 'object' && (report as any).recommended_action ? (
                  <div className="leading-relaxed opacity-90">{(report as any).recommended_action}</div>
                ) : (
                  <div className="leading-relaxed opacity-90">
                    Freeze implicated accounts pending investigation. Immediate escalation to law enforcement recommended.
                    Request enhanced due diligence on account holders and beneficial owners.
                  </div>
                )}
              </div>
            </div>

            <div className="flex gap-3 mt-8 pt-6 border-t border-gray-300">
              <button 
                onClick={() => {
                  // In a real app, this would open an editor
                  alert('Edit functionality would open a rich text editor for the STR draft');
                }}
                disabled={!report}
                className="flex-1 px-6 py-3 border border-gray-400 text-gray-600 hover:bg-gray-100 transition-colors rounded-lg text-sm flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Edit3 className="w-4 h-4" />
                Edit draft
              </button>
              <button 
                onClick={handleSubmit}
                disabled={!report || submitting || submitted}
                className="flex-1 px-6 py-3 bg-[#E31E24] text-white hover:bg-[#d4183d] transition-colors rounded-lg text-sm font-bold flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed" 
                style={{ fontFamily: 'Syne' }}
              >
                {submitting ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Submitting...
                  </>
                ) : submitted ? (
                  <>
                    <CheckCircle className="w-4 h-4" />
                    Submitted
                  </>
                ) : (
                  <>
                    Submit to FIU-IND
                    <ExternalLink className="w-4 h-4" />
                  </>
                )}
              </button>
            </div>
            <div className="mt-4 text-center text-[10px] text-gray-600" style={{ fontFamily: 'DM Mono' }}>
              Submission will create immutable blockchain record
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
